spring:
  application:
    name: exe

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:1420
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - X-Request-Id
    allow-credentials: true
    max-age: 3600

  security:
    jwt:
      access-secret: ${JWT_ACCESS_SECRET}
      refresh-secret: ${JWT_REFRESH_SECRET}
      refresh-hash-secret: ${JWT_HASH_REFRESH_SECRET}
      access-expiration-ms: 900000
      refresh-expiration-ms: 2592000000

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

  rate-limit:
    enable: true
    requests-per-minute: 100

  otp:
    expire-minutes: 5
    length: 6
    max-attempts: 5

  cookie:
    secure: false
    refresh-max-age: 2592000
    same-site: Lax
  seed:
    default-pet-code: "MONKI"
    default-personality-code: "SWEET"
    daily-free-usage: 120
    default-violation-minutes: 5
    personalities:
      - code: "SWEET"
        name: "Sweet Assistant"
        description: "Always encouraging, gentle, and positive."
        premium: false
      - code: "STRICT"
        name: "Strict Assistant"
        description: "Disciplined, straightforward, and unyielding."
        premium: false
      - code: "MEAN"
        name: "Mean Assistant"
        description: "Challenging, provocative, and roasts your ego mercilessly."
        premium: true
    pets:
      - code : "MONKI"
        name : "Monkey"
        description : "A playful and mischievous companion that loves to swing from trees and eat bananas."
        premium : false
        image-url: "https://res.cloudinary.com/dlkcf2b8w/image/upload/v1781511641/MONKI_vtf7p6.png"
      - code : "PANDO"
        name: "Panda"
        description: "A gentle and cuddly companion that loves to eat bamboo and nap in the sun."
        premium: false
        image-url: "https://res.cloudinary.com/dlkcf2b8w/image/upload/v1781511641/PANDO_gs0n1c.png"
      - code : "PIGGY"
        name : "Pig"
        description: "A cute and friendly companion that loves to roll in the mud and eat snacks."
        premium: true
        image-url: "https://res.cloudinary.com/dlkcf2b8w/image/upload/v1781511641/PIGGY_kky3tf.png"
      - code : "FROGI"
        name : "Frog"
        description: "A lively and energetic companion that loves to hop around and catch flies."
        premium: true
        image-url: "https://res.cloudinary.com/dlkcf2b8w/image/upload/v1781511641/FROGI_dxvowf.png"
  ai-cloud:
    base-url: https://openrouter.ai/api/v1
    api-key: ${AI_CLOUD_API_KEY}
    model: "google/gemini-2.5-flash"
    timeout-seconds: 10

